# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  CL:
    runs-on: ubuntu-latest
    
    services:
      postgre:
        image: postgres
        env:
          POSTGRES_DB: SOS_DOTNET_TEST_DB
          POSTGRES_USER: SOS_DOTNET_ADMIN
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Update database
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef migrations add Init --project "./src/SimpleOnlineStore_Dotnet"
        dotnet ef database update --project "./src/SimpleOnlineStore_Dotnet" --connection "Server=localhost;Port=5432;Database=SOS_DOTNET_TEST_DB;Username=SOS_DOTNET_ADMIN;Password=admin;IncludeErrorDetail=true"
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
    - name: Test
      run: dotnet test --no-build --verbosity m
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
    # - name: Codecov
    #   uses: codecov/codecov-action@v1.5.2
